feature_set : {'euclidean_cfid':'o',
                    'euclidean_pristine_cfid':'o',
                    'hellinger_cfid':'||',
                    'hellinger_l2_cfid':'o',
                    'hellinger_l1_cfid':'xx',
                    'hellinger_minmax_cfid':'||',
                    'hellinger_pristine_cfid':'||',
                    'hellinger_pristine_l2_cfid':'o',
                    'hellinger_pristine_l1_cfid':'xx',
                    'hellinger_pristine_minmax_cfid':'||',
                    'pca_cfid':'+++',
                    'best_pca':'++',
                    'kernelpca_cfid':'xx',
                    'cfid':'*',
                    'chem_dist0_cfid':'*',
                    'kazeev':'--',
                    'reduced_kazeev':'--',
                    'eo_chem_cfid':'..',
                    'vpa_divi_eo_chem_cfid': '||',
                    'vpa_mult_eo_chem_cfid': 'xx',
                    'vpa_subs_eo_chem_cfid': '--',
                    }