database:
- 2dmd
dataset:
- all_density
feature_set:
- vpa_divi_chem_tvd_l1_pristine_cfid
- vpa_divi_chem_emd_l1_pristine_alldist_cfid
- vpa_mult_chem_hellinger_l1_pristine_cfid
- tvd_l1_pristine_alldist_cfid
- vpa_mult_chem_cfid
- vpa_mult_chem_hellinger_l1_pristine_alldist_cfid
- vpa_divi_chem_hellinger_l1_pristine_cfid
- emd_l1_pristine_alldist_cfid
- tvd_l1_pristine_cfid
- vpa_divi_chem_hellinger_l1_pristine_alldist_cfid
- vpa_mult_chem_dist0_cfid
- hellinger_l1_pristine_cfid
- vpa_subs_chem_dist0_cfid
- emd_l1_pristine_cfid
- vpa_subs_chem_tvd_l1_pristine_cfid
- vpa_subs_chem_hellinger_l1_pristine_cfid
- vpa_subs_chem_emd_l1_pristine_cfid
- vpa_subs_chem_cfid
- hellinger_l1_pristine_alldist_cfid
- vpa_mult_chem_tvd_l1_pristine_cfid
- cfid
- vpa_divi_chem_tvd_l1_pristine_alldist_cfid
- vpa_divi_chem_dist0_cfid
- vpa_subs_chem_emd_l1_pristine_alldist_cfid
- vpa_mult_chem_tvd_l1_pristine_alldist_cfid
- chem_dist0_cfid
- vpa_mult_chem_emd_l1_pristine_alldist_cfid
- vpa_subs_chem_hellinger_l1_pristine_alldist_cfid
- vpa_mult_chem_emd_l1_pristine_cfid
- vpa_subs_chem_tvd_l1_pristine_alldist_cfid
- vpa_divi_chem_emd_l1_pristine_cfid
- vpa_divi_chem_cfid
model:
  type:
  - CatBoostRegressor
target_column:
- formation_energy_per_site
- homo_lumo_gap_min
